### ISSUE TITLE
Powvideo issue [Solution]

### ISSUE THREAD

**Issue by lscofield** [vb6rocod/utils#1]
Powvideo not working: return Parse error: syntax error, unexpected '(', expecting variable (T_VARIABLE) or '{' or '$'.
NOTE if I get the v.mp4 file directly from the unpacked eval script the link not working, return wrong ip

**Comment by lscofield** [comment]
[Solution] You need to change "body" to "div:first" in preg_match_all and str_replace

**Comment by lscofield** [comment]
I test it and it's working fine

**Comment by vb6rocod** [comment]
fix
