### ISSUE TITLE
Streamtape ASN Error

### ISSUE THREAD

**Issue by xcoders-hub** [vb6rocod/utils#14]
Nice to see your code but if i try to getheader of retrieve url. The url shows correctly but when opening it shows ASN Mismatch. Any idea what's going wrong with my ip?
here is the code i used. 
$link= the link we get through this code.
`$url= $link;

$headers = @get_headers($url);
$final_url = "";
foreach ($headers as $h)
{
    if (substr($h,0,10) == 'Location: ')
    {
    $final_url = trim(substr($h,10));
    break;
    }
}
echo $url;`

**Comment by vb6rocod** [comment]
They solve this problem, I have a similar problem early this morning but now seems to work.

**Comment by xcoders-hub** [comment]
How ? Please add above lines of code in streamtape and see the result.
